# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.srcs/sources_1/bd/Zynq_proc/ip/Zynq_proc_processing_system7_0_0/Zynq_proc_processing_system7_0_0.xci
# IP: The module: 'Zynq_proc_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.srcs/sources_1/bd/Zynq_proc/ip/Zynq_proc_processing_system7_0_0/Zynq_proc_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_proc_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.srcs/sources_1/bd/Zynq_proc/ip/Zynq_proc_processing_system7_0_0/Zynq_proc_processing_system7_0_0.xci
# IP: The module: 'Zynq_proc_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.srcs/sources_1/bd/Zynq_proc/ip/Zynq_proc_processing_system7_0_0/Zynq_proc_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_proc_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
