# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zynq_base_constraints.xdc

# Block Designs: bd/Zynq_proc/Zynq_proc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_proc || ORIG_REF_NAME==Zynq_proc} -quiet] -quiet

# IP: bd/Zynq_proc/ip/Zynq_proc_processing_system7_0_0/Zynq_proc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_proc_processing_system7_0_0 || ORIG_REF_NAME==Zynq_proc_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_proc/ip/Zynq_proc_xlconcat_0_0/Zynq_proc_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_proc_xlconcat_0_0 || ORIG_REF_NAME==Zynq_proc_xlconcat_0_0} -quiet] -quiet

# IP: bd/Zynq_proc/ip/Zynq_proc_xlconcat_1_0/Zynq_proc_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_proc_xlconcat_1_0 || ORIG_REF_NAME==Zynq_proc_xlconcat_1_0} -quiet] -quiet

# XDC: bd/Zynq_proc/Zynq_proc_ooc.xdc
