# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.cache/wt [current_project]
set_property parent.project_path /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.srcs/sources_1/bd/Zynq_proc/hdl/Zynq_proc_wrapper.vhd
add_files /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.srcs/sources_1/bd/Zynq_proc/Zynq_proc.bd
set_property used_in_implementation false [get_files -all /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.srcs/sources_1/bd/Zynq_proc/ip/Zynq_proc_processing_system7_0_0/Zynq_proc_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.srcs/sources_1/bd/Zynq_proc/Zynq_proc_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.srcs/constrs_1/new/Zynq_base_constraints.xdc
set_property used_in_implementation false [get_files /home/stavros/zu3eg/EBAZ4205_Petalinux_Base/EBAZ4205_Petalinux_Base.srcs/constrs_1/new/Zynq_base_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Zynq_proc_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Zynq_proc_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Zynq_proc_wrapper_utilization_synth.rpt -pb Zynq_proc_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
